### ISSUE TITLE
python3で実行できない

### ISSUE THREAD

**Issue by KiyoshiroKawanabe** [open-rdc/force_plate#2]
$ python3 force_plate.py
で、実行できない。

エラー文
> Traceback (most recent call last):
>   File "force_plate.py", line 10, in <module>
>     from PyQt4 import QtGui
> ModuleNotFoundError: No module named 'PyQt4'

**Comment by KiyoshiroKawanabe** [comment]
# python2で実行時のエラー

Traceback (most recent call last):
  File "force_plate.py", line 167, in <module>
    main = Window()
  File "force_plate.py", line 50, in __init__
    start_signal = bytes.fromhex('100204FF32001003CA')
AttributeError: type object 'str' has no attribute 'fromhex'

**Comment by yasuohayashibara** [comment]
PyQt5に対応しました．

**Comment by yasuohayashibara** [comment]
実行できたので，issueを閉じます．
